@echo off
echo Starting ScapeScope...
echo.
echo Starting backend server...
start "Backend Server" cmd /k "npm run proxy"
echo.
echo Starting frontend server...
start "Frontend Server" cmd /k "npm run dev"
echo.
echo Both servers are starting...
echo Frontend will be available at: http://localhost:5173
echo Backend will be available at: http://localhost:3001
echo.
echo Press any key to close this window...
pause > nul 